services:
  cdb:
    image: mysql:latest
    container_name: cdb
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_USER: chat
      MYSQL_PASS: 1234

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"

volumes:
  mysql_volume: